### ISSUE TITLE
使用qrcodejs报错

### ISSUE THREAD

**Issue by shijianzhong** [davidshimjs/qrcodejs#198]
Error
Looks like something broke!

        
Error: No input text
    at Object.create (/root/wxserver/wechatserve/node_modules/_qrcode@1.3.3@qrcode/lib/core/qrcode.js:480:11)
    at /root/wxserver/wechatserve/node_modules/_qrcode@1.3.3@qrcode/lib/server.js:71:27

**Comment by M76chao** [comment]
这个是你自己调用出错，慢慢找吧
